

services:
  stream:
    container_name: stream

    build:
      context: ./src
    ports:
      - "8080:8080"
      - "8081:8081"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"